# 4ihhe00gt2jusvej916soa9sv0 clientid
# secret kc4shn87ct6v9mbp8mer8dmmu1f1hg9vihilo2h350eh6c5o1sk
server:
  port: 8082
app:
  url: http://localhost:8080
cognito:
  rooturl: https://ellin.auth.us-east-1.amazoncognito.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TA0Csivga
